export const PLAYLIST_ID = "PLMs6l5ELgAZVmvoHdbmyPhms1yPG2UApV";

export const playlistSnapshot = [
  ["FTqX59tGPD8", "Trust in God | Aware Worship feat Mark Gutierrez", "Theo's Music", "6:34"],
  ["Kkc8wJcmuGg", "Hezekiah Walker & The LFT Church Choir - I Will Bless The Lord (Filtered Instrumental)", "FiltrdJamz", "4:10"],
  ["CgX2EUd1OX0", "I Will Bless The Lord - instrumental - Hezekiah Walker", "John Alexaz", "4:08"],
  ["2geicdMZAJM", "Hezekiah Walker, The Love Fellowship Choir - Grateful (Lyrics)", "Hip Hop/R&B Lyrics", "6:56"],
  ["ip4WOXSyXYs", "I Need You To Survive Karaoke (Short Version)", "Professing Praise", "3:28"],
  ["acsZyrQUWwQ", "My Life Is In Your Hand (Instrumental)", "Crossroad College Ministry", "5:34"],
  ["kxSKTNCKPwQ", "Glorious by Martha Munizzi Instrumental with Lyrics", "Belle Julian", "4:20"],
  ["BXJnkH42TeM", "Grateful by Hezekiah Walker — Instrumental w/Lyrics", "Worship Instrumentals for Today's Church", "5:52"],
  ["gd_i_yivgEY", "Faithful Is Our God Instrumental", "Tracy Sims", "5:05"],
  ["2Q5LmhF3o4E", "Joshua Troop - Everybody Clap Your Hands | Instrumental w/Lyrics", "NLC Praise & Worship", "4:52"],
  ["QvN5jwBVR4M", "Michael W. Smith - Agnus Dei (karaoke)", "MYDA music", "5:22"],
  ["_5SbtAw7WX4", "Just Want to Praise You — Extended Instrumental with Lyrics", "thachase34", "6:20"],
  ["6qZkAFC-M2E", "I Will Bless The Lord — Pastor Hezekiah Walker", "Jimmie Zaccai", "3:34"],
  ["86hPHr5g46w", "I Call Him Up with Lyrics", "Greg Griffin", "6:45"],
  ["jUYb3877ZhY", "Oh Lord How Excellent — Lyric and Instrumental", "Jimmie Zaccai", "5:24"],
  ["jd8djtilG4A", "Hezekiah Walker - Grateful | Instrumental", "NLC Praise & Worship", "6:56"],
  ["5_iob6lOUOI", "Aware Worship - Trust In God (Featuring Mark Gutierrez)", "Aware Worship", "6:23"],
  ["gIPMllUV12o", "My Life Is in Your Hands - Kirk Franklin", "Camila Moinhos", "5:36"],
  ["P3eWDEcCmIY", "GOCC Western Region Mass Choir", "GOCC California", "24:23"],
  ["hOWPUtml4Lc", "I Just Want to Praise You — Maurette Clark Brown", "Lighthouse Assembly of Believers", "4:59"],
  ["d1PZiJrqr9A", "One True Gospel — Bubby Fann feat. Praise Beyond", "DarkChild Gospel", "3:54"],
  ["2gsqoLytuxQ", "Worship Medley by Trey McLaughlin & SOZ", "DRockStar45", "8:43"],
  ["jT2kf-cZfVY", "One True Gospel (Instrumental) — Bubby Fann", "John Alexaz", "6:09"],
  ["w03xyz66qso", "Pastor Mike Jr. - I Got It (Instrumental)", "For His Kingdom Instrumentals", "4:07"],
  ["pw5Cr3rIWdU", "Trey McLaughlin and SOZ - Worship Medley (Instrumental)", "John Alexaz", "8:44"],
  ["NkCqY8ZP854", "Why We Sing with Lyrics — Kirk Franklin", "Power Music Divine", "5:54"],
  ["QCqf7L9dm_0", "Awesome God — Kirk Franklin with Lyrics", "SBCYAM", "3:48"],
  ["VJ2plsPtlPA", "I Will Bless The Lord — Pastor Hezekiah Walker", "Ms. P and Company", "3:34"],
  ["S3O_iuuF0Cw", "Joshua Troop - Everybody Clap Your Hands - Lyrics", "City of Joy Fellowship", "4:52"],
] as const;
